void ins0NNN();
void ins00E0();
void ins00EE();
void ins1NNN(unsigned short address);
void ins2NNN(unsigned short address);
void ins3XNN(unsigned short registerX, unsigned short value);
void ins4XNN(unsigned short registerX, unsigned short value);
void ins5XY0(unsigned short registerX, unsigned short registerY);
void ins6XNN(unsigned short registerX, unsigned short value);
void ins7XNN(unsigned short registerX, unsigned short value);
void ins8XY0(unsigned short registerX, unsigned short registerY);
void ins8XY1(unsigned short registerX, unsigned short registerY);
void ins8XY2(unsigned short registerX, unsigned short registerY);
void ins8XY3(unsigned short registerX, unsigned short registerY);
void ins8XY4(unsigned short registerX, unsigned short registerY);
void ins8XY5(unsigned short registerX, unsigned short registerY);
void ins8XY6(unsigned short registerX);
void ins8XY7(unsigned short registerX, unsigned short registerY);
void ins8XYE(unsigned short registerX, unsigned short registerY);
void ins9XY0(unsigned short registerX, unsigned short registerY);
void insANNN(unsigned short address);
void insBNNN(unsigned short address);
void insCXNN(unsigned short registerX, unsigned short value);
void insDXYN(unsigned short registerX, unsigned short registerY, unsigned short spriteHeight);
void insEX9E(unsigned short registerX);
void insEXA1(unsigned short registerX);
void insFX07(unsigned short registerX);
void insFX0A(unsigned short registerX);
void insFX15(unsigned short registerX);
void insFX18(unsigned short registerX);
void insFX1E(unsigned short registerX);
void insFX29(unsigned short registerX);
void insFX33(unsigned short registerX);
void insFX55(unsigned short registerX);
void insFX65(unsigned short registerX);

void decode(unsigned short opcode);